/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: TampaJoey (https://sketchfab.com/TampaJoey)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-buildings-pack-low-poly-game-ready-333a430644b34e688aecfdc874f4cbf2
Title: Sci-fi Buildings Pack (low-poly, game ready)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SciFiBuildingsPack(props) {
  const { nodes, materials } = useGLTF('/models/sci-fi_buildings_pack.glb')

  // Helper to clone and override material
  function getOverlayMaterial(baseMaterial) {
    const mat = baseMaterial.clone();
    mat.color.set(props.colorOverlay); // Overlay color
    mat.emissive = mat.color.clone();
    mat.emissiveIntensity = 1.5; // Strong emission
    mat.transparent = true;
    mat.opacity = 0.7; // Semi-transparent overlay
    return mat;
  }

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[802.577, 0, -233.117]} rotation={[0, -0.3, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building2_T_B2windows_0.geometry}
            material={getOverlayMaterial(materials.T_B2windows)}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building2_T_B2base_white_0.geometry}
            material={getOverlayMaterial(materials.T_B2base_white)}
          />
        </group>
        <group position={[-1576.172, 0, -551.746]} rotation={[0, -0.314, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building6_T_B6base_white_0.geometry}
            material={getOverlayMaterial(materials.T_B6base_white)}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building6_T_B6windows_0.geometry}
            material={getOverlayMaterial(materials.T_B6windows)}
          />
        </group>
        <group position={[491.923, 0, 299.06]} rotation={[0, 0.185, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building6b_T_B6base_gray_0.geometry}
            material={getOverlayMaterial(materials.T_B6base_gray)}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building6b_T_B6windows_0.geometry}
            material={getOverlayMaterial(materials.T_B6windows)}
          />
        </group>
        <group position={[1750.113, 0, 299.5]} rotation={[0, 0.237, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building2b_T_B2windows_0.geometry}
            material={getOverlayMaterial(materials.T_B2windows)}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building2b_T_B2base_gray_0.geometry}
            material={getOverlayMaterial(materials.T_B2base_gray)}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building1_T_B1base_white_0.geometry}
          material={getOverlayMaterial(materials.T_B1base_white)}
          position={[-1622.124, 0, 743.129]}
          rotation={[0, -0.367, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building3_T_B3base_white_0.geometry}
          material={getOverlayMaterial(materials.T_B3base_white)}
          position={[-1160.69, 0, 11.781]}
          rotation={[0, 0.18, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building4_T_B4base_white_0.geometry}
          material={getOverlayMaterial(materials.T_B4base_white)}
          position={[-1027.447, 0, 330.177]}
          rotation={[0, -0.942, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building5_T_B5base_white_0.geometry}
          material={getOverlayMaterial(materials.T_B5base_white)}
          position={[-371.154, 0, 378.878]}
          rotation={[-Math.PI, 0.472, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building1b_T_B1base_gray_0.geometry}
          material={getOverlayMaterial(materials.T_B1base_gray)}
          position={[271.594, 0, 580.062]}
          rotation={[0, 0.475, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building3b_T_B3base_gray_0.geometry}
          material={getOverlayMaterial(materials.T_B3base_gray)}
          position={[1096.954, 0, -494.714]}
          rotation={[0, 0.18, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building5b_T_B5base_gray_0.geometry}
          material={getOverlayMaterial(materials.T_B5base_gray)}
          position={[1517.091, 0, 961.83]}
          rotation={[-Math.PI, -0.282, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building4b_T_B4base_gray_0.geometry}
          material={getOverlayMaterial(materials.T_B4base_gray)}
          position={[1919.172, 0, 731.193]}
          rotation={[-Math.PI, -0.711, -Math.PI]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/sci-fi_buildings_pack.glb')
