/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const link = '/models/free_stylized_skybox_cityskyline.glb'

export function SkyBoxCitySkyLine(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_Material_0.geometry}
        material={materials.Material}
        scale={0.003}
      />
    </group>
  )
}

useGLTF.preload(link)
